# Generated by Django 2.2.11 on 2021-01-14 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('happiness_level', models.FloatField(max_length=5)),
                ('happiness_date', models.DateField()),
                ('userteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Teams')),
            ],
        ),
    ]
