# Generated by Django 2.2.11 on 2021-01-14 02:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210113_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='happiness_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='happiness_level',
        ),
        migrations.CreateModel(
            name='UserHappiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('happiness_date', models.DateField(unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
            ],
        ),
    ]
