# Generated by Django 2.2.11 on 2021-01-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210113_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhappiness',
            name='happiness_date',
            field=models.DateField(),
        ),
    ]
